spring:
  application:
    name: supay-boot-demo
server:
  port: 15888

logging:
  config: classpath:log4j2.xml

supay:
  channel:
    alipay:
      appId:
      appSecret:
      mchId:
      mchSecretKey:
      rootKey:
    wechat:
      appId:
      appSecret:
      mchId:
      mchSecretKey:
